version: "3.8"

services:
  gateway:
    build: client-gateaway 
    container_name: client-gateaway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres-db:5432/mydatabase
    networks:
      - backend-network

  students-ms:
    build: students-ms
    container_name: students-ms
    ports:
      - "3001:3001"
    depends_on:
      - postgres-students
    environment:
      PORT: 3001
      DATABASE_URL: postgres://dinara:dinara1234@postgres-students:5432/students
    networks:
      - backend-network

  courses-ms:
    build: courses-ms
    container_name: courses-ms
    ports:
      - "3002:3002"
    depends_on:
      - postgres-courses
    environment:
      PORT: 3002
      DATABASE_URL: postgres://dinara:dinara1234@postgres-courses:5432/courses
    networks:
      - backend-network

  postgres-students:
    image: postgres:15
    container_name: postgres-students
    restart: always
    environment:
      - POSTGRES_DB=students
      - POSTGRES_USER=dinara
      - POSTGRES_PASSWORD=dinara1234
    volumes:
      - pgdata_students:/var/lib/postgresql/data
      - ./students-ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "5433:5432"
    networks:
      - backend-network

  postgres-courses:
    image: postgres:15
    container_name: postgres-courses
    restart: always
    environment:
      - POSTGRES_DB=courses
      - POSTGRES_USER=dinara
      - POSTGRES_PASSWORD=dinara1234
    volumes:
      - pgdata_courses:/var/lib/postgresql/data
      - ./courses-ms/db/init.sql:/docker-entrypoint-initdb.d/init.sql    
    ports:
      - "5434:5432"
    networks:
      - backend-network
      
  postgres:
    image: postgres:15  
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres_data:
    name: postgres_data
  pgdata_students:
    name: pgdata_students
  pgdata_courses:
    name: pgdata_courses

networks:
  backend-network:
    driver: bridge
