version: "3.8"

services:
  gateway:
    build: client-gateaway 
    container_name: client-gateaway
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydatabase
    networks:
      - backend-network

  postgres:
    image: postgres:15  
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  backend-network:
    driver: bridge